name: Update CSV from Google Sheets (R)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system libraries (required for gsheet dependencies)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install gsheet package and dependencies
        run: |
          Rscript -e 'install.packages("gsheet", repos = "https://cloud.r-project.org")'

      - name: Run the R script
        run: |
          Rscript write_to_csv/write_csv.R

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add write_to_csv/data.csv
          git commit -m "Update data.csv from Google Sheets" || echo "No changes to commit"
          git push
